# Generated by Django 5.0.2 on 2024-12-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('arrival_time', models.IntegerField()),
                ('service_time', models.IntegerField()),
            ],
        ),
    ]
