# Generated by Django 5.0.2 on 2024-12-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='time_difference',
            field=models.IntegerField(default=0, help_text='الفرق الزمني بين هذا العميل والعميل السابق (بالدقائق)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='arrival_time',
            field=models.IntegerField(help_text='وقت وصول العميل (بالدقائق)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='service_time',
            field=models.IntegerField(help_text='وقت الخدمة للعميل (بالدقائق)'),
        ),
    ]
