# Generated by Django 5.0.2 on 2024-12-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0004_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
