# Generated by Django 5.0.2 on 2024-12-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0005_customer_probability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='time_difference',
            new_name='difference_time',
        ),
    ]
