# Generated by Django 5.0.2 on 2024-12-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0006_rename_time_difference_customer_difference_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='service_time_probability',
            field=models.FloatField(blank=True, help_text='احتمالية ظهور وقت الخدمة', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='probability',
            field=models.FloatField(blank=True, help_text='احتمالية ظهور الفارق الزمني', null=True),
        ),
    ]
