# Generated by Django 5.0.2 on 2024-12-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0007_customer_service_time_probability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_customers', models.IntegerField()),
                ('min_arrived_time', models.IntegerField()),
                ('max_arrived_time', models.IntegerField()),
            ],
        ),
    ]
