# Generated by Django 5.0.2 on 2024-12-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0008_customerarrival'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RenameField(
            model_name='customerarrival',
            old_name='min_arrived_time',
            new_name='max_serves_time',
        ),
    ]
