# Generated by Django 5.0.2 on 2024-12-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0009_delete_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerarrival',
            name='max_serves2_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
